### PR TITLE
Fix temp dir permission docker error

### PR DESCRIPTION
**Pull request by crouffer**
- Remove dependance on user home directory for temporary storage.  User directories ("~/") are not always created for Unix service accounts.
- Create the temporary directory using tempfile.mkdtemp()
- Store the directory path in a singleton-like structure accessed via a function call

This fixes issue https://github.com/shaypal5/skift/issues/6 by creating the tempdir in an OS/environment agnostic way, and does not rely on the users' home directory being writeable.

### CODE REVIEW

**Comment by crouffer** [comment]
@shaypal5 Can you please take a look at this, and merge if you see fit?

Thanks

**Comment by crouffer** [comment]
Closing this:  Need to add one more commit before pull request

**Comment by shaypal5** [comment]
Cool! Waiting for the final PR! :)

**Comment by crouffer** [comment]
@shaypal5  These changes allow the user to set an environment variable to control the temp dir location.  If the variable isn't set, use tempfile.mkdtemp instead.

**Comment by shaypal5** [comment]
Hey @crouffer ,

This looks great from looking at it briefly, but unfortantely I've made a mistake in the way I have set up travis to upload `pytest` reports to codecov (it did this only if all tests pass).

I've now fixed this, and so it seems like travis (and later the codecov bot, I guess), will report on failures directly in pull requests. Anyway, as you also see (hopefully), your PR fails some tests:
https://travis-ci.org/shaypal5/skift/builds/470554210

So, now three things are needed to make the PR complete:
1. Please fix whatever is broken. :)  Let me know if home directories or env vars on travis give you trouble.
2. Add tests to maintain test coverage on 100%. You should see it both in the end of each travis build, and here for each commit (codecov is supposed to comment here on the PR on test coverage).
3. Add documentation - which means an appropriate paragraph on the README.rst file, and in any new function it might be missing (just the crucial stuff, you know).

I know it's a bit of a hassle, but it's worth it to have it done all nicely and all.

Cheers,
Shay

**Comment by crouffer** [comment]
Thanks Shay - I'll try to get this fixed later today, or this weekend.

**Comment by crouffer** [comment]
Hi @shaypal5

I've fixed the failing tests, and added tests to ensure full code coverage.

**Comment by shaypal5** [comment]
Yes! It looks great! Amazing!
Care to add a line to the readme, just stating how to set the temp folder path?

**Comment by crouffer** [comment]
Added SKIFT_TEMP_DIR description to the README

**Comment by shaypal5** [comment]
Amazing! You're done! What a champ!

**Pull request merged**
