### PR TITLE
WIP: core: support autotune

### PR DESCRIPTION
**Pull request by dimidd**
Hi, added support for auto-tuning. Please LMK if you support this direction, and I'll add documentation and more tests to make it a mergeable PR. 

Signed-off-by: Dimid Duchovny <dimidd@localize.city>

### CODE REVIEW

**Comment by shaypal5** [comment]
Great! :)

I moved the CI from travis to GitHub Actions. Please rebase your commit over the current head of master so we can have tests and linting running for this PR, and then continue to add documentation and tests.

**Comment by shaypal5** [comment]
@dimidd 
Can you see the coverage issues on this PR?

**Comment by dimidd** [comment]
Fixed

**Review by shaypal5 — APPROVED** [review]
Awesome work. Outstanding, man. :)

**Pull request merged**
